# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  projectcore:
    image: projectcore
    build:
      context: .
      dockerfile: src/project.core/Dockerfile
    ports:
      - 5010:5010

  db:
    image: postgres:14.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    